server:
  port: 5959

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/markmercado1/Reservaciones.git # repositorio
          searchPaths:
            - config-data
          default-label: main

  security:
    user:
      name: root
      password: 123456